"""add emission_factors

Revision ID: 0b69cebd3171
Revises: 583de812c643
Create Date: 2025-08-28 03:14:31.746712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b69cebd3171'
down_revision: Union[str, None] = '583de812c643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('input_unit', sa.String(), nullable=False),
    sa.Column('factor_value', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_factors_id'), 'emission_factors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emission_factors_id'), table_name='emission_factors')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
