"""init schema

Revision ID: 4441aa646105
Revises: 
Create Date: 2025-08-27 21:25:29.454684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4441aa646105'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activities_id', table_name='activities')
    op.drop_index('ix_activities_org_id', table_name='activities')
    op.drop_table('activities')
    op.drop_index('ix_sources_id', table_name='sources')
    op.drop_index('ix_sources_org_id', table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('sources_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('storage_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sources_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_sources_org_id', 'sources', ['org_id'], unique=False)
    op.create_index('ix_sources_id', 'sources', ['id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scope', postgresql.ENUM('scope1', 'scope2', 'scope3', name='scopeenum'), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_quality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name='activities_source_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='activities_pkey')
    )
    op.create_index('ix_activities_org_id', 'activities', ['org_id'], unique=False)
    op.create_index('ix_activities_id', 'activities', ['id'], unique=False)
    # ### end Alembic commands ###
